[package]
name = "rusty-q2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
filename = "gamex86_64"
crate-type = ["dylib"]

[dependencies]
